name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # استخدام أحدث إصدار من Python

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev \
        libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
        libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-0 gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good libffi-dev
        pip install buildozer cython==0.29.19

    - name: Install Android SDK
      run: |
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk/cmdline-tools
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest
        ls -l $HOME/android-sdk/cmdline-tools/latest/bin  # التحقق من وجود sdkmanager
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-30" || echo "Failed to run sdkmanager"

    - name: Set up environment variables
      run: |
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/30.0.3:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Remove existing Flet-kivy directory
      run: |
        if [ -d "Flet-kivy" ]; then
          rm -rf Flet-kivy
        fi

    - name: Clone Flet-kivy repository
      run: |
        git clone --depth=1 https://github.com/5tu7r7u/Flet-kivy.git

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Clean Buildozer cache
      run: buildozer android clean
