name: Android Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install required dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lib32z1 lib32ncurses6 libbz2-1.0 lib32stdc++6 openjdk-11-jdk
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -r requirements.txt

      # Install Android SDK Command-line Tools
      - name: Install Android SDK Command-line Tools
        run: |
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          export PATH=$HOME/android-sdk/cmdline-tools/cmdline-tools/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "build-tools;30.0.3" "platforms;android-30"

      # Install Buildozer
      - name: Install Buildozer
        run: |
          pip install buildozer

      # Build the Android APK
      - name: Build APK
        run: |
          buildozer android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: ./bin/*.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy steps (تخصيص خطوات النشر الخاصة بك)
      - name: Deploy application
        run: |
          echo "Deploying application..."
